Importing Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

Loading dataset

In [34]:
#Reading the datasets and displaying the first 5 rows of each dataset
sales = pd.read_csv("../data/raw/sales.csv")
features = pd.read_csv("../data/raw/features.csv")
stores = pd.read_csv("../data/raw/stores.csv")

Dataset Overview

In [35]:
print("SALES")
display(sales.head())

print("FEATURES")
display(features.head())

print("STORES")
display(stores.head())

SALES

   store_id  department        date  weekly_sales  is_holiday
0         1           1  2022-01-01     119075.96           1
1         1           2  2022-01-01     119107.85           1
2         1           3  2022-01-01      84369.88           1
3         1           4  2022-01-01      88445.24           1
4         1           5  2022-01-01      65159.85           1

FEATURES

,store_id,date,temperature,fuel_price,markdown_1,markdown_2,markdown_3,markdown_4,markdown_5,cpi,unemployment,is_holiday,holiday_name,season
0,1,2022-01-01,97.57,4.83,10334.49,5905.86,5261.52,7098.43,876.08,203.52,3.32,1,New Year,Winter
1,1,2022-01-08,46.03,3.67,1356.75,2486.21,1427.01,983.27,2442.13,196.91,8.62,0,NaN,Winter
2,1,2022-01-15,25.96,5.46,3861.22,596.15,22.09,2854.11,3180.86,267.48,8.40,0,NaN,Winter
3,1,2022-01-22,25.92,3.58,579.35,2589.31,2493.19,1158.14,286.01,217.32,5.28,0,NaN,Winter
4,1,2022-01-29,78.37,4.41,4436.06,1416.64,478.38,2496.36,3423.53,247.35,8.40,0,NaN,Winter

STORES

   store_id store_type  store_size region
0         1          A      213810  North
1         2          C       31639   East
2         3          B      102098  South
3         4          B       88289  North
4         5          A      218696  North

In [ ]:
#Checking the shape of each dataset
print("Sales Shape:", sales.shape)
print("Features Shape:", features.shape)
print("Stores Shape:", stores.shape)

Sales Shape: (156000, 5)
Features Shape: (7800, 14)
Stores Shape: (50, 4)

In [ ]:
#Checking the columns of each dataset
print("Sales Columns")
print(sales.columns.tolist())

print("\nFeatures Columns")
print(features.columns.tolist())

print("\nStores Columns")
print(stores.columns.tolist())

Sales Columns
['store_id', 'department', 'date', 'weekly_sales', 'is_holiday']

Features Columns
['store_id', 'date', 'temperature', 'fuel_price', 'markdown_1', 'markdown_2', 'markdown_3', 'markdown_4', 'markdown_5', 'cpi', 'unemployment', 'is_holiday', 'holiday_name', 'season']

Stores Columns
['store_id', 'store_type', 'store_size', 'region']

Data types of each dataset

In [ ]:
sales.info()

features.info()

stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 156000 entries, 0 to 155999
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   store_id      156000 non-null  int64
 1   department    156000 non-null  int64
 2   date          156000 non-null  str
 3   weekly_sales  156000 non-null  float64
 4   is_holiday    156000 non-null  int64
dtypes: float64(1), int64(3), str(1)
memory usage: 6.0 MB
<class 'pandas.DataFrame'>
RangeIndex: 7800 entries, 0 to 7799
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      7800 non-null   int64
 1   date          7800 non-null   str
 2   temperature   7800 non-null   float64
 3   fuel_price    7800 non-null   float64
 4   markdown_1    7800 non-null   float64
 5   markdown_2    7800 non-null   float64
 6   markdown_3    7800 non-null   float64
 7   markdown_4    7800 non-null   float64
 8   markdown_5    7800 non-null   float64
 9   cpi           7800 non-null   float64
 10  unemployment  7800 non-null   float64
 11  is_holiday    7800 non-null   int64
 12  holiday_name  900 non-null    str
 13  season        7800 non-null   str
dtypes: float64(9), int64(2), str(3)
memory usage: 853.3 KB
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    50 non-null     int64
 1   store_type  50 non-null     str
 2   store_size  50 non-null     int64
 3   region      50 non-null     str
dtypes: int64(2), str(2)
memory usage: 1.7 KB

Missing values

In [ ]:
sales.isnull().sum() #checking for null values in sales dataset

store_id        0
department      0
date            0
weekly_sales    0
is_holiday      0
dtype: int64

In [ ]:
features.isnull().sum() #checking for null values in features dataset

store_id           0
date               0
temperature        0
fuel_price         0
markdown_1         0
markdown_2         0
markdown_3         0
markdown_4         0
markdown_5         0
cpi                0
unemployment       0
is_holiday         0
holiday_name    6900
season             0
dtype: int64

In [ ]:
stores.isnull().sum() #checking for null values in stores dataset

store_id      0
store_type    0
store_size    0
region        0
dtype: int64

Duplicate records

In [ ]:
print("Sales:", sales.duplicated().sum())

print("Features:", features.duplicated().sum())

print("Stores:", stores.duplicated().sum())

Sales: 0
Features: 0
Stores: 0

Summary statistics

In [ ]:
sales.describe()

            store_id   department   weekly_sales     is_holiday
count  156000.000000  156000.0000  156000.000000  156000.000000
mean       25.500000      10.5000   56503.488802       0.115385
std        14.430916       5.7663   46717.490663       0.319487
min         1.000000       1.0000     819.660000       0.000000
25%        13.000000       5.7500   21255.962500       0.000000
50%        25.500000      10.5000   43394.870000       0.000000
75%        38.000000      15.2500   79604.107500       0.000000
max        50.000000      20.0000  505958.730000       1.000000

In [ ]:
features.describe()

,store_id,temperature,fuel_price,markdown_1,markdown_2,markdown_3,markdown_4,markdown_5,cpi,unemployment,is_holiday
count,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000
mean,25.500000,59.875755,3.986344,2831.840176,1708.091033,2295.922200,1982.042679,2561.790629,240.469559,6.485572,0.115385
std,14.431795,23.116172,0.864077,1977.953750,1187.693694,1579.374985,1351.528967,1769.798978,34.602955,2.015121,0.319506
min,1.000000,20.020000,2.500000,0.180000,0.200000,1.010000,1.130000,0.140000,180.000000,3.000000,0.000000
25%,13.000000,39.942500,3.240000,1308.727500,787.155000,1095.917500,969.917500,1198.375000,211.027500,4.720000,0.000000
50%,25.500000,60.065000,3.970000,2652.495000,1612.570000,2174.595000,1862.980000,2417.900000,240.945000,6.490000,0.000000
75%,38.000000,79.910000,4.750000,4027.545000,2423.002500,3212.695000,2790.137500,3600.245000,270.445000,8.220000,0.000000
max,50.000000,99.970000,5.500000,10977.070000,6599.720000,8798.150000,7692.880000,9891.190000,299.990000,10.000000,1.000000

In [ ]:
stores.describe()

       store_id     store_size
count  50.00000      50.000000
mean   25.50000  136626.440000
std    14.57738   53620.213818
min     1.00000   31639.000000
25%    13.25000   93030.000000
50%    25.50000  140736.500000
75%    37.75000  179781.500000
max    50.00000  218696.000000

In [ ]:
sales.describe(include="object") #checking the summary statistics of the sales dataset for object data types

C:\Users\Sharad Vidhate\AppData\Local\Temp\ipykernel_17336\2732439258.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  sales.describe(include="object")

              date
count       156000
unique         156
top     2022-01-01
freq          1000

In [ ]:
features.describe(include="object") #checking the summary statistics of the features dataset for object data types

C:\Users\Sharad Vidhate\AppData\Local\Temp\ipykernel_17336\1406358493.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  features.describe(include="object")

              date holiday_name  season
count         7800          900    7800
unique         156            5       4
top     2022-01-01    Christmas  Summer
freq            50          250    2000

In [ ]:
stores.describe(include="object") #checking the summary statistics of the stores dataset for object data types

C:\Users\Sharad Vidhate\AppData\Local\Temp\ipykernel_17336\4126274614.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  stores.describe(include="object")

       store_type region
count          50     50
unique          3      4
top             A   East
freq           26     16

In [ ]:
#Checking the number of unique values in each object column of the sales dataset
for col in sales.select_dtypes(include="object"):
    print(col)
    print(sales[col].nunique())
    print("-"*40)

date
156
----------------------------------------

C:\Users\Sharad Vidhate\AppData\Local\Temp\ipykernel_17336\3642572678.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in sales.select_dtypes(include="object"):

In [ ]:
#Checking the number of unique values in each object column of the features dataset
for col in features.select_dtypes(include="object"):
    print(col)
    print(features[col].nunique())
    print("-"*40)

date
156
----------------------------------------
holiday_name
5
----------------------------------------
season
4
----------------------------------------

C:\Users\Sharad Vidhate\AppData\Local\Temp\ipykernel_17336\892461928.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in features.select_dtypes(include="object"):

In [ ]:
#Checking the number of unique values in each object column of the stores dataset
for col in stores.select_dtypes(include="object"):
    print(col)
    print(stores[col].nunique())
    print("-"*40)

store_type
3
----------------------------------------
region
4
----------------------------------------

C:\Users\Sharad Vidhate\AppData\Local\Temp\ipykernel_17336\3260035655.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in stores.select_dtypes(include="object"):

In [ ]:
#Converting the date columns in sales and features datasets to datetime format
sales["date"] = pd.to_datetime(sales["date"])

features["date"] = pd.to_datetime(features["date"])

In [ ]:
sales.info() #checking the data types of the sales dataset after converting the date column to datetime format

<class 'pandas.DataFrame'>
RangeIndex: 156000 entries, 0 to 155999
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   store_id      156000 non-null  int64
 1   department    156000 non-null  int64
 2   date          156000 non-null  datetime64[us]
 3   weekly_sales  156000 non-null  float64
 4   is_holiday    156000 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(3)
memory usage: 6.0 MB

In [ ]:
#Checking the start and end dates of the sales and features datasets
print("Sales Start :", sales["date"].min())
print("Sales End   :", sales["date"].max())

print("Features Start :", features["date"].min())
print("Features End   :", features["date"].max())

Sales Start : 2022-01-01 00:00:00
Sales End   : 2024-12-21 00:00:00
Features Start : 2022-01-01 00:00:00
Features End   : 2024-12-21 00:00:00

Initial business understanding

In [40]:
sales["department"].nunique()
print("Number of unique departments in sales dataset:", sales["department"].nunique())

sales["store_id"].nunique()
print("Number of unique store IDs in sales dataset:", sales["store_id"].nunique())

features["store_id"].nunique()
print("Number of unique store IDs in features dataset:", features["store_id"].nunique())

Number of unique departments in sales dataset: 20
Number of unique store IDs in sales dataset: 50
Number of unique store IDs in features dataset: 50

In [36]:
stores["store_type"].value_counts() #checking the count of each store type
print("Count of each store type:")
print(stores["store_type"].value_counts())

Count of each store type:
store_type
A    26
B    16
C     8
Name: count, dtype: int64

In [39]:
stores["region"].value_counts() #checking the count of stores in each region
print("Count of stores in each region:")
print(stores["region"].value_counts())

Count of stores in each region:
region
East     16
North    13
South    12
West      9
Name: count, dtype: int64