# Retail Supply Chain Analytics

## Exploratory Data Analysis (EDA)

### Objective: The objective of this notebook is to understand the structure, quality and business context of the datasets before designing the ETL pipeline.

The analysis performed in this notebook includes:

- Importing required libraries
- Loading datasets
- Exploring dataset structure
- Assessing data quality
- Converting data types
- Understanding business entities
- Identifying relationships between datasets

In [29]:
# =====================================================
# IMPORT LIBRARIES
# =====================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Configure pandas display options for better readability
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

## 1. Load Datasets

Load the three raw datasets into Pandas DataFrames for exploration.

In [30]:
# =====================================================
# LOAD DATASETS
# =====================================================

sales = pd.read_csv("../data/raw/sales.csv")
features = pd.read_csv("../data/raw/features.csv")
stores = pd.read_csv("../data/raw/stores.csv")

## 2. Dataset Preview

Display the first five rows of each dataset to understand their overall structure.

In [31]:
# =====================================================
# DATASET PREVIEW
# =====================================================

print("=" * 70)
print("SALES DATASET")
print("=" * 70)
display(sales.head())

print("=" * 70)
print("FEATURES DATASET")
print("=" * 70)
display(features.head())

print("=" * 70)
print("STORES DATASET")
print("=" * 70)
display(stores.head())

======================================================================
SALES DATASET
======================================================================

   store_id  department        date  weekly_sales  is_holiday
0         1           1  2022-01-01     119075.96           1
1         1           2  2022-01-01     119107.85           1
2         1           3  2022-01-01      84369.88           1
3         1           4  2022-01-01      88445.24           1
4         1           5  2022-01-01      65159.85           1

======================================================================
FEATURES DATASET
======================================================================

,store_id,date,temperature,fuel_price,markdown_1,markdown_2,markdown_3,markdown_4,markdown_5,cpi,unemployment,is_holiday,holiday_name,season
0,1,2022-01-01,97.57,4.83,10334.49,5905.86,5261.52,7098.43,876.08,203.52,3.32,1,New Year,Winter
1,1,2022-01-08,46.03,3.67,1356.75,2486.21,1427.01,983.27,2442.13,196.91,8.62,0,NaN,Winter
2,1,2022-01-15,25.96,5.46,3861.22,596.15,22.09,2854.11,3180.86,267.48,8.40,0,NaN,Winter
3,1,2022-01-22,25.92,3.58,579.35,2589.31,2493.19,1158.14,286.01,217.32,5.28,0,NaN,Winter
4,1,2022-01-29,78.37,4.41,4436.06,1416.64,478.38,2496.36,3423.53,247.35,8.40,0,NaN,Winter

======================================================================
STORES DATASET
======================================================================

   store_id store_type  store_size region
0         1          A      213810  North
1         2          C       31639   East
2         3          B      102098  South
3         4          B       88289  North
4         5          A      218696  North

## 3. Dataset Dimensions

Determine the number of rows and columns in each dataset.

In [32]:
# =====================================================
# DATASET DIMENSIONS
# =====================================================

print(f"Sales Dataset Shape    : {sales.shape}")
print(f"Features Dataset Shape : {features.shape}")
print(f"Stores Dataset Shape   : {stores.shape}")

Sales Dataset Shape    : (156000, 5)
Features Dataset Shape : (7800, 14)
Stores Dataset Shape   : (50, 4)

## 4. Dataset Columns

Inspect the available columns in each dataset.

In [33]:
# =====================================================
# COLUMN NAMES
# =====================================================

print("Sales Columns")
print(sales.columns.tolist())

print("\nFeatures Columns")
print(features.columns.tolist())

print("\nStores Columns")
print(stores.columns.tolist())

Sales Columns
['store_id', 'department', 'date', 'weekly_sales', 'is_holiday']

Features Columns
['store_id', 'date', 'temperature', 'fuel_price', 'markdown_1', 'markdown_2', 'markdown_3', 'markdown_4', 'markdown_5', 'cpi', 'unemployment', 'is_holiday', 'holiday_name', 'season']

Stores Columns
['store_id', 'store_type', 'store_size', 'region']

## 5. Data Type Inspection

Inspect the data types and identify columns that may require conversion before analysis.

In [34]:
# =====================================================
# DATA TYPES
# =====================================================

print("=" * 70)
print("SALES DATASET")
print("=" * 70)
sales.info()

print("\n" + "=" * 70)
print("FEATURES DATASET")
print("=" * 70)
features.info()

print("\n" + "=" * 70)
print("STORES DATASET")
print("=" * 70)
stores.info()

======================================================================
SALES DATASET
======================================================================
<class 'pandas.DataFrame'>
RangeIndex: 156000 entries, 0 to 155999
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   store_id      156000 non-null  int64
 1   department    156000 non-null  int64
 2   date          156000 non-null  str
 3   weekly_sales  156000 non-null  float64
 4   is_holiday    156000 non-null  int64
dtypes: float64(1), int64(3), str(1)
memory usage: 6.0 MB

======================================================================
FEATURES DATASET
======================================================================
<class 'pandas.DataFrame'>
RangeIndex: 7800 entries, 0 to 7799
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      7800 non-null   int64
 1   date          7800 non-null   str
 2   temperature   7800 non-null   float64
 3   fuel_price    7800 non-null   float64
 4   markdown_1    7800 non-null   float64
 5   markdown_2    7800 non-null   float64
 6   markdown_3    7800 non-null   float64
 7   markdown_4    7800 non-null   float64
 8   markdown_5    7800 non-null   float64
 9   cpi           7800 non-null   float64
 10  unemployment  7800 non-null   float64
 11  is_holiday    7800 non-null   int64
 12  holiday_name  900 non-null    str
 13  season        7800 non-null   str
dtypes: float64(9), int64(2), str(3)
memory usage: 853.3 KB

======================================================================
STORES DATASET
======================================================================
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    50 non-null     int64
 1   store_type  50 non-null     str
 2   store_size  50 non-null     int64
 3   region      50 non-null     str
dtypes: int64(2), str(2)
memory usage: 1.7 KB

## 6. Missing Value Analysis

Identify missing values to assess data quality and determine whether cleaning is required.

In [35]:
# =====================================================
# MISSING VALUE ANALYSIS
# =====================================================

print("Sales Dataset")
display(sales.isnull().sum())

print("Features Dataset")
display(features.isnull().sum())

print("Stores Dataset")
display(stores.isnull().sum())

Sales Dataset

store_id        0
department      0
date            0
weekly_sales    0
is_holiday      0
dtype: int64

Features Dataset

store_id           0
date               0
temperature        0
fuel_price         0
markdown_1         0
markdown_2         0
markdown_3         0
markdown_4         0
markdown_5         0
cpi                0
unemployment       0
is_holiday         0
holiday_name    6900
season             0
dtype: int64

Stores Dataset

store_id      0
store_type    0
store_size    0
region        0
dtype: int64

## 7. Duplicate Record Analysis

Check for duplicate records before performing any aggregations or modelling.

In [36]:
# =====================================================
# DUPLICATE RECORD ANALYSIS
# =====================================================

print(f"Sales Dataset Duplicates    : {sales.duplicated().sum()}")
print(f"Features Dataset Duplicates : {features.duplicated().sum()}")
print(f"Stores Dataset Duplicates   : {stores.duplicated().sum()}")

Sales Dataset Duplicates    : 0
Features Dataset Duplicates : 0
Stores Dataset Duplicates   : 0

## 8. Summary Statistics

Generate descriptive statistics for both numerical and categorical variables.

In [37]:
# =====================================================
# SUMMARY STATISTICS
# =====================================================

print("Sales Dataset")
display(sales.describe())

print("Features Dataset")
display(features.describe())

print("Stores Dataset")
display(stores.describe())

print("Sales Dataset (Categorical)")
display(sales.describe(include="object"))

print("Features Dataset (Categorical)")
display(features.describe(include="object"))

print("Stores Dataset (Categorical)")
display(stores.describe(include="object"))

Sales Dataset

            store_id   department   weekly_sales     is_holiday
count  156000.000000  156000.0000  156000.000000  156000.000000
mean       25.500000      10.5000   56503.488802       0.115385
std        14.430916       5.7663   46717.490663       0.319487
min         1.000000       1.0000     819.660000       0.000000
25%        13.000000       5.7500   21255.962500       0.000000
50%        25.500000      10.5000   43394.870000       0.000000
75%        38.000000      15.2500   79604.107500       0.000000
max        50.000000      20.0000  505958.730000       1.000000

Features Dataset

,store_id,temperature,fuel_price,markdown_1,markdown_2,markdown_3,markdown_4,markdown_5,cpi,unemployment,is_holiday
count,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000,7800.000000
mean,25.500000,59.875755,3.986344,2831.840176,1708.091033,2295.922200,1982.042679,2561.790629,240.469559,6.485572,0.115385
std,14.431795,23.116172,0.864077,1977.953750,1187.693694,1579.374985,1351.528967,1769.798978,34.602955,2.015121,0.319506
min,1.000000,20.020000,2.500000,0.180000,0.200000,1.010000,1.130000,0.140000,180.000000,3.000000,0.000000
25%,13.000000,39.942500,3.240000,1308.727500,787.155000,1095.917500,969.917500,1198.375000,211.027500,4.720000,0.000000
50%,25.500000,60.065000,3.970000,2652.495000,1612.570000,2174.595000,1862.980000,2417.900000,240.945000,6.490000,0.000000
75%,38.000000,79.910000,4.750000,4027.545000,2423.002500,3212.695000,2790.137500,3600.245000,270.445000,8.220000,0.000000
max,50.000000,99.970000,5.500000,10977.070000,6599.720000,8798.150000,7692.880000,9891.190000,299.990000,10.000000,1.000000

Stores Dataset

       store_id     store_size
count  50.00000      50.000000
mean   25.50000  136626.440000
std    14.57738   53620.213818
min     1.00000   31639.000000
25%    13.25000   93030.000000
50%    25.50000  140736.500000
75%    37.75000  179781.500000
max    50.00000  218696.000000

Sales Dataset (Categorical)

C:\Users\Sharad Vidhate\AppData\Local\Temp\ipykernel_6232\2794033811.py:15: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(sales.describe(include="object"))

              date
count       156000
unique         156
top     2022-01-01
freq          1000

Features Dataset (Categorical)

C:\Users\Sharad Vidhate\AppData\Local\Temp\ipykernel_6232\2794033811.py:18: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(features.describe(include="object"))

              date holiday_name  season
count         7800          900    7800
unique         156            5       4
top     2022-01-01    Christmas  Summer
freq            50          250    2000

Stores Dataset (Categorical)

C:\Users\Sharad Vidhate\AppData\Local\Temp\ipykernel_6232\2794033811.py:21: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(stores.describe(include="object"))

       store_type region
count          50     50
unique          3      4
top             A   East
freq           26     16

## 9. Categorical Variable Exploration

Determine the number of unique values in categorical columns.

In [38]:
# =====================================================
# UNIQUE VALUES IN CATEGORICAL COLUMNS
# =====================================================

datasets = {
    "Sales": sales,
    "Features": features,
    "Stores": stores
}

for dataset_name, dataframe in datasets.items():

    print("=" * 70)
    print(dataset_name.upper())
    print("=" * 70)

    categorical_columns = dataframe.select_dtypes(include="object").columns

    if len(categorical_columns) == 0:
        print("No categorical columns found.\n")
        continue

    for column in categorical_columns:
        print(f"{column}: {dataframe[column].nunique()} unique values")

======================================================================
SALES
======================================================================
date: 156 unique values
======================================================================
FEATURES
======================================================================
date: 156 unique values
holiday_name: 5 unique values
season: 4 unique values
======================================================================
STORES
======================================================================
store_type: 3 unique values
region: 4 unique values

C:\Users\Sharad Vidhate\AppData\Local\Temp\ipykernel_6232\97489612.py:17: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = dataframe.select_dtypes(include="object").columns
C:\Users\Sharad Vidhate\AppData\Local\Temp\ipykernel_6232\97489612.py:17: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = dataframe.select_dtypes(include="object").columns
C:\Users\Sharad Vidhate\AppData\Local\Temp\ipykernel_6232\97489612.py:17: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = dataframe.select_dtypes(include="object").columns

## 10. Date Conversion

Convert the date columns from string format to datetime for time-series analysis.

In [39]:
# =====================================================
# DATE CONVERSION
# =====================================================

sales["date"] = pd.to_datetime(sales["date"])
features["date"] = pd.to_datetime(features["date"])

print("Updated Sales Dataset")

sales.info()

print("\nUpdated Features Dataset")

features.info()

Updated Sales Dataset
<class 'pandas.DataFrame'>
RangeIndex: 156000 entries, 0 to 155999
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   store_id      156000 non-null  int64
 1   department    156000 non-null  int64
 2   date          156000 non-null  datetime64[us]
 3   weekly_sales  156000 non-null  float64
 4   is_holiday    156000 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(3)
memory usage: 6.0 MB

Updated Features Dataset
<class 'pandas.DataFrame'>
RangeIndex: 7800 entries, 0 to 7799
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      7800 non-null   int64
 1   date          7800 non-null   datetime64[us]
 2   temperature   7800 non-null   float64
 3   fuel_price    7800 non-null   float64
 4   markdown_1    7800 non-null   float64
 5   markdown_2    7800 non-null   float64
 6   markdown_3    7800 non-null   float64
 7   markdown_4    7800 non-null   float64
 8   markdown_5    7800 non-null   float64
 9   cpi           7800 non-null   float64
 10  unemployment  7800 non-null   float64
 11  is_holiday    7800 non-null   int64
 12  holiday_name  900 non-null    str
 13  season        7800 non-null   str
dtypes: datetime64[us](1), float64(9), int64(2), str(2)
memory usage: 853.3 KB

## 11. Temporal Coverage

Determine the time period covered by the datasets.

In [40]:
# =====================================================
# DATE RANGE
# =====================================================

print(f"Sales Dataset Start Date    : {sales['date'].min()}")
print(f"Sales Dataset End Date      : {sales['date'].max()}")

print()

print(f"Features Dataset Start Date : {features['date'].min()}")
print(f"Features Dataset End Date   : {features['date'].max()}")

Sales Dataset Start Date    : 2022-01-01 00:00:00
Sales Dataset End Date      : 2024-12-21 00:00:00

Features Dataset Start Date : 2022-01-01 00:00:00
Features Dataset End Date   : 2024-12-21 00:00:00

## 12. Initial Business Understanding

Explore key business entities before performing deeper analysis.

In [41]:
# =====================================================
# INITIAL BUSINESS UNDERSTANDING
# =====================================================

print(f"Number of Stores                 : {sales['store_id'].nunique()}")
print(f"Number of Departments            : {sales['department'].nunique()}")
print(f"Number of Feature Store Records  : {features['store_id'].nunique()}")

print("\nStore Types")
display(stores["store_type"].value_counts())

print("\nRegional Distribution")
display(stores["region"].value_counts())

Number of Stores                 : 50
Number of Departments            : 20
Number of Feature Store Records  : 50

Store Types

store_type
A    26
B    16
C     8
Name: count, dtype: int64

Regional Distribution

region
East     16
North    13
South    12
West      9
Name: count, dtype: int64

## 13. Initial Findings

### Key Findings

- The Sales dataset contains weekly sales transactions for each department within each store.
- The Features dataset contains external variables such as temperature, fuel price, CPI, unemployment and promotional markdowns that may influence sales.
- The Stores dataset contains descriptive information about each retail store.

### Data Quality Assessment

- No duplicate records were identified in any dataset.
- No missing values were found in the Sales or Stores datasets.
- The only missing values occur in `holiday_name`, which likely indicates weeks that are not associated with a holiday rather than missing data.
- Date columns were converted from string to `datetime` format to enable time-series analysis.

### Next Steps

The next phase of the project will focus on:

1. Sales trend analysis
2. Store performance analysis
3. Department performance analysis
4. Holiday impact on sales
5. Correlation analysis
6. Feature engineering
7. ETL pipeline design

## 14. Data Integration

To perform comprehensive business analysis, the three datasets are merged into a single analytical dataset.

The merge is performed as follows:

- Sales ↔ Features using `store_id` and `date`
- Resulting_dataset ↔ Stores using `store_id`

This combined dataset will be used for exploratory analysis and visualisations.

In [42]:
# =====================================================
# DATA INTEGRATION
# =====================================================

# Merge Sales and Features datasets
analysis_df = pd.merge(
    sales,
    features,
    on=["store_id", "date"],
    how="left"
)

# Merge the resulting dataset with Stores
analysis_df = pd.merge(
    analysis_df,
    stores,
    on="store_id",
    how="left"
)

print(f"Combined Dataset Shape: {analysis_df.shape}")

analysis_df.head()

Combined Dataset Shape: (156000, 20)

,store_id,department,date,weekly_sales,is_holiday_x,temperature,fuel_price,markdown_1,markdown_2,markdown_3,markdown_4,markdown_5,cpi,unemployment,is_holiday_y,holiday_name,season,store_type,store_size,region
0,1,1,2022-01-01,119075.96,1,97.57,4.83,10334.49,5905.86,5261.52,7098.43,876.08,203.52,3.32,1,New Year,Winter,A,213810,North
1,1,2,2022-01-01,119107.85,1,97.57,4.83,10334.49,5905.86,5261.52,7098.43,876.08,203.52,3.32,1,New Year,Winter,A,213810,North
2,1,3,2022-01-01,84369.88,1,97.57,4.83,10334.49,5905.86,5261.52,7098.43,876.08,203.52,3.32,1,New Year,Winter,A,213810,North
3,1,4,2022-01-01,88445.24,1,97.57,4.83,10334.49,5905.86,5261.52,7098.43,876.08,203.52,3.32,1,New Year,Winter,A,213810,North
4,1,5,2022-01-01,65159.85,1,97.57,4.83,10334.49,5905.86,5261.52,7098.43,876.08,203.52,3.32,1,New Year,Winter,A,213810,North

## 15. Merge Validation

After merging, validate that:

- The number of rows has not changed unexpectedly.
- Store information has been merged correctly.
- No new missing values have been introduced due to incorrect join keys.

In [43]:
# =====================================================
# MERGE VALIDATION
# =====================================================

print("=" * 70)
print("MERGED DATASET INFORMATION")
print("=" * 70)

print(f"Shape of merged dataset: {analysis_df.shape}")

print("\nMissing values after merge:")
display(analysis_df.isnull().sum())

======================================================================
MERGED DATASET INFORMATION
======================================================================
Shape of merged dataset: (156000, 20)

Missing values after merge:

store_id             0
department           0
date                 0
weekly_sales         0
is_holiday_x         0
temperature          0
fuel_price           0
markdown_1           0
markdown_2           0
markdown_3           0
markdown_4           0
markdown_5           0
cpi                  0
unemployment         0
is_holiday_y         0
holiday_name    138000
season               0
store_type           0
store_size           0
region               0
dtype: int64

## 16. Holiday Column Validation

The merged dataset contains two holiday indicator columns because both the Sales and Features datasets included an `is_holiday` field.

Before removing one of them, verify that both columns contain identical values.

In [44]:
# =====================================================
# HOLIDAY COLUMN VALIDATION
# =====================================================

# Check whether both holiday indicator columns are identical.
holiday_match = (analysis_df["is_holiday_x"] == analysis_df["is_holiday_y"]).all()

print(f"Are both holiday columns identical? {holiday_match}")

Are both holiday columns identical? True

In [45]:
# =====================================================
# REMOVE DUPLICATE HOLIDAY COLUMN
# =====================================================

analysis_df = analysis_df.drop(columns=["is_holiday_y"])

analysis_df = analysis_df.rename(
    columns={"is_holiday_x": "is_holiday"}
)

analysis_df.head()

,store_id,department,date,weekly_sales,is_holiday,temperature,fuel_price,markdown_1,markdown_2,markdown_3,markdown_4,markdown_5,cpi,unemployment,holiday_name,season,store_type,store_size,region
0,1,1,2022-01-01,119075.96,1,97.57,4.83,10334.49,5905.86,5261.52,7098.43,876.08,203.52,3.32,New Year,Winter,A,213810,North
1,1,2,2022-01-01,119107.85,1,97.57,4.83,10334.49,5905.86,5261.52,7098.43,876.08,203.52,3.32,New Year,Winter,A,213810,North
2,1,3,2022-01-01,84369.88,1,97.57,4.83,10334.49,5905.86,5261.52,7098.43,876.08,203.52,3.32,New Year,Winter,A,213810,North
3,1,4,2022-01-01,88445.24,1,97.57,4.83,10334.49,5905.86,5261.52,7098.43,876.08,203.52,3.32,New Year,Winter,A,213810,North
4,1,5,2022-01-01,65159.85,1,97.57,4.83,10334.49,5905.86,5261.52,7098.43,876.08,203.52,3.32,New Year,Winter,A,213810,North